### Задание на повторение материала 

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел
чисел от 12 до 24 невключительно

In [105]:
import numpy as np

In [106]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах
метода reshape число -1.

In [107]:
a1 = a.reshape(12, 1).copy()
print(f'a1 = \n {a1}')

a2 = a.reshape(6, 2).copy()
print(f'a2 = \n {a2}')

a3 = a.reshape(4, 3).copy()
print(f'a3 = \n {a3}')

a4 = a.reshape(3, 4).copy()
print(f'a4 = \n {a4}')

a5 = a.reshape(2, 6).copy()
print(f'a5 = \n {a5}')

a1 = 
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
a2 = 
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
a3 = 
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
a4 = 
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
a5 = 
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах
метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для
строк).

In [108]:
a1 = a.reshape(-1, 1).copy()
print(f'a1 = \n {a1}')

a2 = a.reshape(-1, 2).copy()
print(f'a2 = \n {a2}')

a3 = a.reshape(4, -1).copy()
print(f'a3 = \n {a3}')

a4 = a.reshape(3, -1).copy()
print(f'a4 = \n {a4}')

a5 = a.reshape(2, -1).copy()
print(f'a5 = \n {a5}')

a1 = 
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
a2 = 
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
a3 = 
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
a4 = 
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
a5 = 
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [109]:
a1.ndim

2

Массив Numpy, состоящий из одного столбца и 12 строк - двумерный массив.

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [110]:
m = np.random.randn(3, 4)
m

array([[-0.7868971 ,  0.11874356, -0.75686314,  0.49336691],
       [-0.83940431, -1.01502185, -0.34251968,  1.88446401],
       [-0.27091291, -1.45171934, -1.08015896,  2.56507656]])

In [111]:
n = m.flatten()
n

array([-0.7868971 ,  0.11874356, -0.75686314,  0.49336691, -0.83940431,
       -1.01502185, -0.34251968,  1.88446401, -0.27091291, -1.45171934,
       -1.08015896,  2.56507656])

In [112]:
m.size == n.size

True

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [113]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [114]:
b = a.reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [115]:
a.ndim == b.ndim

False

Массив "а" - одномерный, массив "b" - двумерный

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [116]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [117]:
b = np.ones((2+1, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [118]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [119]:
v.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [120]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [121]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [122]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [123]:
B = np.dot(A, At) 
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [124]:
B.size

16

In [125]:
np.linalg.det(B) == np.linalg.matrix_rank(B)

False

Обратную матрицу для матрицы "В" вычислить невозможно, потому что не все её строки являются линейно независимыми

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [126]:
np.random.seed(42)
np.random.random(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [127]:
c = np.random.randint(0, 16, (16))
c

array([ 2,  6, 10, 10,  7,  4,  3,  7,  7,  2,  5,  4,  1,  7, 11, 13])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [128]:
C = c.reshape(4, 4)
C

array([[ 2,  6, 10, 10],
       [ 7,  4,  3,  7],
       [ 7,  2,  5,  4],
       [ 1,  7, 11, 13]])

In [129]:
D = B + C * 10
D

array([[ 25,  74, 123, 132],
       [ 84,  90, 116, 192],
       [ 93, 106, 199, 252],
       [ 42, 192, 322, 432]])

In [130]:
d = np.linalg.det(D)
d.round()

-25281600.0

In [131]:
r = np.linalg.matrix_rank(D)
r

4

In [132]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00188912,  0.00544902,  0.00906588, -0.00828745],
       [ 0.04419973,  0.02648567, -0.03311183, -0.00596165],
       [ 0.01216062, -0.01919499,  0.01614771, -0.00460414],
       [-0.02889216,  0.0020062 ,  0.00179894,  0.00920195]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [133]:
D_inv = np.where(D_inv > 0, 1, 0)
D_inv

array([[1, 1, 1, 0],
       [1, 1, 0, 0],
       [1, 0, 1, 0],
       [0, 1, 1, 1]])

In [134]:
E = np.where(D_inv == 1, B, C)
E

array([[  5,  14,  23,  10],
       [ 14,  50,   3,   7],
       [ 23,   2, 149,   4],
       [  1, 122, 212, 302]])